---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.3

suites:
  - name: default
    run_list:
      - recipe[codenamephp_php::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: "5.6"
    run_list:
      - recipe[codenamephp_php::5.6]
    verifier:
      inspec_tests:
        - test/smoke/5.6
    attributes:
  - name: "7.1"
    run_list:
      - recipe[codenamephp_php::7.1]
    verifier:
      inspec_tests:
        - test/smoke/7.1
    attributes: