---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.3

suites:
  - name: default
    run_list:
      - recipe[codenamephp_php::add_sury_repository]
      - recipe[codenamephp_php::7.2] # a php version needs to be installed for composer to be installed
      - recipe[codenamephp_php::composer]
      - recipe[codenamephp_php::xdebug]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: "5.6"
    run_list:
      - recipe[codenamephp_php::5.6]
    verifier:
      inspec_tests:
        - test/smoke/5.6
    attributes:
  - name: "7.1"
    run_list:
      - recipe[codenamephp_php::7.1]
    verifier:
      inspec_tests:
        - test/smoke/7.1
    attributes:
  - name: "7.2"
    run_list:
      - recipe[codenamephp_php::7.2]
    verifier:
      inspec_tests:
        - test/smoke/7.2
    attributes: