---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-9.1

suites:
  - name: default
    run_list:
      - recipe[chef.cookbook.php::default]
      - recipe[chef.cookbook.php::add_sury_repository]
      - recipe[chef.cookbook.php::7.1]
      - recipe[chef.cookbook.php::composer]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
