name: Draft Release
on:
  push:
    branches: [ release ]
    paths-ignore:
      - '**.md'

jobs:
  draft_release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: calculate next version
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: draft release
        uses: release-drafter/release-drafter@v5
        with:
          version: ${{ format('{0}', steps.version.outputs.next-version) }}
          tag: ${{ format('{0}', steps.version.outputs.next-version) }}
          name: ${{ format('{0}', steps.version.outputs.next-version) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create changelog
        uses: charmixer/auto-changelog-action@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_labels: "duplicate,question,invalid,wontfix,skip-changelog"
          future_release: ${{ format('{0}', steps.version.outputs.next-version) }}
          release_branch: 'release'

      - name: commit updated changelog
        uses: EndBug/add-and-commit@v5
        with:
          message: "[CHANGELOG] Updated changelog"
          add: "CHANGELOG.md"
          signoff: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}